name: Prepare Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./dist/*"
